[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
admin_instructions = "AH3gT3xA632W86HaGKkuj9995aef3RNrd1jKgBp5NZej"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sebatustra/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
